### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [kevnhowe/codecademy-project-3-the-scoop#1]
On running npm test, these were four errors that come up. All errors were caused by setting the database as a constant. Because the values within database changes. use

`let database = {};`

instead of 

`const database = {};`

errors are as follows;
```

  1) Scoop - server.js:  /comments/:id PUT routes['/comments/:id'].PUT should return a 404 response with a non-existent comment:

      AssertionError: expected 200 to equal 404
      + expected - actual

      -200
      +404
      
      at Context.<anonymous> (test/test.js:288:34)                                                                                                                                             

  2) Scoop - server.js:  /comments/:id DELETE routes['/comments/:id'].DELETE should return a 404 response with a non-existent comment ID:

      AssertionError: expected 204 to equal 404
      + expected - actual

      -204
      +404
      
      at Context.<anonymous> (test/test.js:381:34)

  3) Scoop - server.js:  /commnets/:id/upvote PUT routes['/comments/:id/upvote'].PUT should return a 400 response when supplied a non-existent comment ID:
     TypeError: Cannot read property 'includes' of undefined
      at Object.upvoteComment [as PUT] (server.js:335:33)
      at Context.<anonymous> (test/test.js:450:61)

  4) Scoop - server.js:  /comments/:id/downvote PUT routes['/comments/:id/downvote'].PUT should return a 400 response when supplied a non-existent comment ID:
     TypeError: Cannot read property 'includes' of undefined
      at Object.downvoteComment [as PUT] (server.js:365:35)
      at Context.<anonymous> (test/test.js:536:63)



```

**Comment by kevnhowe** [comment]
oh geez. that was dumb of me. I made the edit just prior to committing without running the unit test afterward. I have fixed and committed the change. Lesson learned. :)

**Comment by kevnhowe** [comment]
Are you able to pull and review the code after successful test?

**Comment by mp1pro** [comment]
The code works fine now.

**Comment by kevnhowe** [comment]
thanks Marvin. Will I get a review?

**Comment by mp1pro** [comment]
Review is complete, all the npm tests passed. 
For further help, contact a express adviser at http://codecademy.com
